module.exports = {
    root: __dirname + '/../',
    pathIgnore: ['*node_modules*']
};

var options = {
    adsafe: false,
    bitwise: true,
    browser: true,
    cap: false,
    confusion: false,
    continue: true,
    css: false,
    debug: false,
    devel: true,
    eqeq: false,
    es5: true,
    evil: true,
    forin: false,
    fragment: false,
    indent: 4,
    maxerr: 300,
    maxlen: 600,
    newcap: true,
    node: true,
    nomen: true,
    on: false,
    passfail: false,
    plusplus: false,
    predef: ['window', 'module', 'util', 'require', 'process', 'exports', 'escape', '__dirname', 'setTimeout', 'io', '_'],
    regexp: true,
    rhino: false,
    safe: false,
    sloppy: true,
    sub: false,
    undef: false,
    unparam: false,
    vars: false,
    white: false,
    widget: false,
    windows: false
};
